excluded:
  - "bin/*"
  - "Script/*"
  - "Generated/*"
  - "Package.swift"
  - "Resources/Localizables/Strings+Generated.swift"

disabled_rules:
  - identifier_name
  - inclusive_language
  - type_name
  - redundant_string_enum_value
  - todo

analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

opt_in_rules:
  - array_init
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - cyclomatic_complexity
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - expiring_todo
  - explicit_init
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - nimble_operator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prohibited_super_call
  - raw_value_for_camel_cased_codable_enum
  - redundant_nil_coalescing
  - required_enum_case
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_whitespace_closing_braces
  - yoda_condition
  - comment_spacing
  - function_body_length
  - file_length
  - line_length
  - type_body_length
  - nesting
  - large_tuple
  - vertical_whitespace
  - force_cast
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - trailing_whitespace

line_length:
  warning: 180
  error: 250
  ignores_comments: true

function_body_length:
  warning: 120
  error: 180

file_length:
  warning: 500
  error: 600

type_body_length:
  warning: 500
  error: 600

vertical_whitespace:
  max_empty_lines: 1

nesting:
  type_level: 6

large_tuple:
  warning: 5
  error: 6

force_cast:
  severity: error

force_try:
  severity: error

force_unwrapping:
  severity: error

implicitly_unwrapped_optional:
  severity: error

custom_rules:
  private_state_finder:
    include: "*.swift"
    name: "Private State"
    regex: "(@State\\s+var)"
    message: "States should be private."
    severity: warning
  sf_safe_symbol:
    name: "Safe SFSymbol"
    message: "Use `SFSafeSymbols` via `systemSymbol` parameters for type safety."
    regex: "(Image\\(systemName:)|(NSImage\\(symbolName:)|(Label[^,]+?,\\s*systemImage:)|(UIApplicationShortcutIcon\\(systemImageName:)"
    severity: warning
